name = "mischooldata_etls"
description = "The ETL Scripts for loading MISchoolData Datasets"
schema = "education"

[tables.school_attendance]
name="school_attendance"
description = "The attendance file published by mischool data filtered to school level"
unit_of_analysis = "Schools"
universe = "Schools in Michigan Districts"
owner = "Center for Educational Performance and Information"
collector = "Michigan Department of Education"
collection_method = "I don't know -- but it this is probably findable and should be recorded (MV)"
collection_reason = "Help residents, educators, and policy makers make informed decisions to improve student success."
source_url = "mischooldata.org"
notes = "The 'error' column is calculated by D3 using this python tool: https://github.com/data-driven-detroit/inequalitytools.git"
cadence = "Yearly -- released in mid September. Calendar site: https://www.mischooldata.org/recently-posted-page/."

[[tables.school_attendance.variables]]
name = "district_code"
description = "The district code of the school measured (connects to eem_districts)"

[[tables.school_attendance.variables]]
name = "building_code"
description = "The building code of the school measured (connects to eem_schools)"

[[tables.school_attendance.variables]]
name = "report_category"
description = "The overarching category for the 'report_subgroup' for filtering the measurement. Filter to 'grade' on this column to get to all students."

[[tables.school_attendance.variables]]
name = "report_subgroup"
description = "The subgroup measured. Filter to 'all' on this column to get to all students."

[[tables.school_attendance.variables]]
name = "total_students"
description = "The count of students in this report category."

[[tables.school_attendance.variables]]
name = "total_students_error"
description = "Error introducted on the 'total_students' measurement from suppression"

[[tables.school_attendance.variables]]
name = "chronically_absent"
description = "The count of chronically absent students (missed more than 10% days, ~18, in a year) in this report category."

[[tables.school_attendance.variables]]
name = "chronically_absent_error"
description = "Error introducted on the 'chronically_absent' measurement from suppression"

[[tables.school_attendance.variables]]
name = "start_date"
description = "The first of July (Q3) before the school year measured."

[[tables.school_attendance.variables]]
name = "end_date"
description = "The last day of June (end Q2) after the school year measured."

[tables.school_attendance.editions.2024-07-01]
edition_date = "2024-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2024\\Raw\\attendance_2024.csv"
start = "2023-07-01"
end = "2024-06-30"
published = "2024-09-17"
acquired = "2025-02-11"

[tables.school_attendance.editions.2023-07-01]
edition_date = "2023-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2023\\Raw\\attendance_2023.csv"
start = "2022-07-01"
end = "2023-06-30"
published = "2023-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2022-07-01]
edition_date = "2022-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2022\\Raw\\attendance_2022.csv"
start = "2021-07-01"
end = "2022-06-30"
published = "2022-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2021-07-01]
edition_date = "2021-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2021\\Raw\\attendance_2021.csv"
start = "2020-07-01"
end = "2021-06-30"
published = "2021-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2020-07-01]
edition_date = "2020-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2020\\Raw\\attendance_2020.csv"
start = "2019-07-01"
end = "2020-06-30"
published = "2020-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2019-07-01]
edition_date = "2019-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2019\\Raw\\attendance_2019.csv"
start = "2018-07-01"
end = "2019-06-30"
published = "2019-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2018-07-01]
edition_date = "2018-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2018\\Raw\\attendance_2018.csv"
start = "2017-07-01"
end = "2018-06-30"
published = "2018-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2017-07-01]
edition_date = "2017-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2017\\Raw\\attendance_2017.csv"
start = "2016-07-01"
end = "2017-06-30"
published = "2017-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2016-07-01]
edition_date = "2016-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2016\\Raw\\attendance_2016.csv"
start = "2015-07-01"
end = "2016-06-30"
published = "2016-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2015-07-01]
edition_date = "2015-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2015\\Raw\\attendance_2015.csv"
start = "2014-07-01"
end = "2015-06-30"
published = "2015-09-17"
acquired = "2023-11-27"

# The Education Entity Master file -- basically the file that contains all
# the school and district information. We geocode this file to become the
# reference for further spatial analysis.
[tables.eem_schools]
name="eem_schools"
description = "The CEPI 'Education Entity Master' file that holds all base information about schools and districts. Filtered to schools, then geocoded with the census geocoder."
unit_of_analysis = "Schools"
universe = "Michigan School buildings (sometimes inactive)"
owner = "CEPI; US Census Bureau (for geocoding)"
collector = "CEPI; US Census Bureau (geocoding)"
# collection_We geocode with census geo"method = "Leave commented if not using"
collection_reason = "Help residents, educators, and policy makers make informed decisions to improve student success."
source_url = "mischooldata.org"
# notes = "Leave commented if not using"
# use_conditions = "Leave commented if not using"
cadence = "Yearly -- released in early February"


[[tables.eem_schools.variables]]
name = "isd_code"
description = "The 2-digit code for the 'intermediate school district' associated with the school."

[[tables.eem_schools.variables]]
name = "isd_name"
description = "The name of the ISD associated with the school"

[[tables.eem_schools.variables]]
name = "district_code"
description = "The 5-digit code for the local district associated with the school."

[[tables.eem_schools.variables]]
name = "district_name"
description = "The name of the district associated with the code."

[[tables.eem_schools.variables]]
name = "building_code"
description = "The 5-digit code associated with the school building itself."

[[tables.eem_schools.variables]]
name = "building_name"
description = "The name of the school or non-school building."

[[tables.eem_schools.variables]]
name = "county_code"
description = "NOT FIPS! The 2-digit code for the county in which the school is located."
standard = "MCIR: https://www.mcir.org/wp-content/uploads/2016/03/Michigan-County-Codes.pdf"

[[tables.eem_schools.variables]]
name = "county_name"
description = "The short name of the county in which the school is located."

[[tables.eem_schools.variables]]
name = "entity_type"
description = "The entity type describes whether the school is charter / not, whether the building is a school or another type of educational facility or ancillary district building"

[[tables.eem_schools.variables]]
name = "school_level"
description = "Whether the school is elementry / middle / high or some combination."

[[tables.eem_schools.variables]]
name = "locale_name"
description = "A small descriptor of the municipality that the school is in, follows the pattern <City | Town | Suburb | Rural>: <Small | Midsize | Large | Distant | Fringe | Remote>. Worth looking into further on a map."

[[tables.eem_schools.variables]]
name = "school_emphasis"
description = "Whether the school is 'general education' or 'alternative' or 'vocational' education, etc."

[[tables.eem_schools.variables]]
name = "setting"
description = "Similar to emphasis, but with more detail on the actual location -- for instance is the school in a juvenile detention facility."

[[tables.eem_schools.variables]]
name = "email_address"
description = "The email address of the school."

[[tables.eem_schools.variables]]
name = "phone_number"
description = "The school phone number."

[[tables.eem_schools.variables]]
name = "street_address"
description = "The school street address"

[[tables.eem_schools.variables]]
name = "city"
description = "The school city"

[[tables.eem_schools.variables]]
name = "state"
description = "The school state"

[[tables.eem_schools.variables]]
name = "zip_code"
description = "The school zip code."

[[tables.eem_schools.variables]]
name = "school_type"
description = "Again, similar to setting and emphasis -- more detailed than emphasis, less so than setting."

[[tables.eem_schools.variables]]
name = "status"
description = "Whether the school is open, closed, empty or pending close."

[[tables.eem_schools.variables]]
name = "matchtype"
description = "Whether the geocoder found an exact or inexact match."

[[tables.eem_schools.variables]]
name = "geometry"
description = "The centroid geometry for the school."

[[tables.eem_schools.variables]]
name = "start_date"
description = "The start date of Q3 of the year the school year begins"

[[tables.eem_schools.variables]]
name = "end_date"
description = "The end date of Q2 of the year the school year ends"

[tables.eem_schools.editions.2024-07-01]
edition_date = "2024-07-01"
notes = "First upload of this dataset"
raw_path = ""
start = "2023-07-01"
end = "2024-06-29"
published = "2024-02-05"
acquired = "2025-02-15"
