[tables.school_attendance]
name="school_attendance"
description = "The attendance file published by mischool data filtered to school level"
unit_of_analysis = "Schools"
universe = "Schools in Michigan Districts"
owner = "Center for Educational Performance and Information"
collector = "Michigan Department of Education"
collection_method = "I don't know -- but it this is probably findable and should be recorded (MV)"
collection_reason = "Help residents, educators, and policy makers make informed decisions to improve student success."
source_url = "mischooldata.org"
notes = "The 'error' column is calculated by D3 using this python tool: https://github.com/data-driven-detroit/inequalitytools.git"
cadence = "Yearly -- released in mid September. Calendar site: https://www.mischooldata.org/recently-posted-page/."

[[tables.school_attendance.variables]]
name = "district_code"
description = "The district code of the school measured (connects to eem_districts)"

[[tables.school_attendance.variables]]
name = "building_code"
description = "The building code of the school measured (connects to eem_schools)"

[[tables.school_attendance.variables]]
name = "report_category"
description = "The overarching category for the 'report_subgroup' for filtering the measurement. Filter to 'grade' on this column to get to all students."

[[tables.school_attendance.variables]]
name = "report_subgroup"
description = "The subgroup measured. Filter to 'all' on this column to get to all students."

[[tables.school_attendance.variables]]
name = "total_students"
description = "The count of students in this report category."

[[tables.school_attendance.variables]]
name = "total_students_error"
description = "Error introducted on the 'total_students' measurement from suppression"

[[tables.school_attendance.variables]]
name = "chronically_absent"
description = "The count of chronically absent students (missed more than 10% days, ~18, in a year) in this report category."

[[tables.school_attendance.variables]]
name = "chronically_absent_error"
description = "Error introducted on the 'chronically_absent' measurement from suppression"

[[tables.school_attendance.variables]]
name = "start_date"
description = "The first of July (Q3) before the school year measured."

[[tables.school_attendance.variables]]
name = "end_date"
description = "The last day of June (end Q2) after the school year measured."

[tables.school_attendance.editions.2024-07-01]
edition_date = "2024-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2024\\Raw\\attendance_2024.csv"
start = "2023-07-01"
end = "2024-06-30"
published = "2024-09-17"
acquired = "2025-02-11"

[tables.school_attendance.editions.2023-07-01]
edition_date = "2023-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2023\\Raw\\attendance_2023.csv"
start = "2022-07-01"
end = "2023-06-30"
published = "2023-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2022-07-01]
edition_date = "2022-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2022\\Raw\\attendance_2022.csv"
start = "2021-07-01"
end = "2022-06-30"
published = "2022-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2021-07-01]
edition_date = "2021-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2021\\Raw\\attendance_2021.csv"
start = "2020-07-01"
end = "2021-06-30"
published = "2021-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2020-07-01]
edition_date = "2020-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2020\\Raw\\attendance_2020.csv"
start = "2019-07-01"
end = "2020-06-30"
published = "2020-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2019-07-01]
edition_date = "2019-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2019\\Raw\\attendance_2019.csv"
start = "2018-07-01"
end = "2019-06-30"
published = "2019-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2018-07-01]
edition_date = "2018-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2018\\Raw\\attendance_2018.csv"
start = "2017-07-01"
end = "2018-06-30"
published = "2018-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2017-07-01]
edition_date = "2017-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2017\\Raw\\attendance_2017.csv"
start = "2016-07-01"
end = "2017-06-30"
published = "2017-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2016-07-01]
edition_date = "2016-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2016\\Raw\\attendance_2016.csv"
start = "2015-07-01"
end = "2016-06-30"
published = "2016-09-17"
acquired = "2023-11-27"

[tables.school_attendance.editions.2015-07-01]
edition_date = "2015-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Chronic absentee\\Data\\2015\\Raw\\attendance_2015.csv"
start = "2014-07-01"
end = "2015-06-30"
published = "2015-09-17"
acquired = "2023-11-27"
