# The Student Counts file -- basically the file that contains all
# the school and district information. We geocode this file to become the
# reference for further spatial analysis.

#TODO: Need to rewrite the content below for Student Counts.
name="student_counts"
description = "The CEPI 'Student Counts' file that holds all base information about schools and districts. Filtered to schools, then geocoded with the census geocoder."
unit_of_analysis = "Schools"
universe = "Michigan School buildings (sometimes inactive)"
owner = "CEPI; US Census Bureau (for geocoding)"
collector = "CEPI; US Census Bureau (geocoding)"
collection_method = "Collected from mischool data then geocoded with Census Bureau Geocoder"
collection_reason = "Help residents, educators, and policy makers make informed decisions to improve student success."
source_url = "mischooldata.org"
# notes = "Leave commented if not using"
# use_conditions = "Leave commented if not using"
cadence = "Yearly -- released in early February"

[[variables]]
name = "schoollevel"
description = "The educational level associated with a school."

[[variables]]
name = "locale_name"
description = "The geographic setting of a school based on its location."

[[variables]]
name = "mistem_name"
description = "The Michigan STEM region associated with a school."

[[variables]]
name = "mistem_code"
description = "The 2-digit code for the Michigan STEM region."

[[variables]]
name = "total_enrollment"
description = "Total number of students enrolled."

[[variables]]
name = "male_enrollment"
description = "Total number of male students enrolled."

[[variables]]
name = "female_enrollment"
description = "Total number of female students enrolled."

[[variables]]
name = "american_indian_enrollment"
description = "Total number of students enrolled who identify as American Indian or Alaska Native."
 
[[variables]]
name = "asian_enrollment"
description = "Total number of students enrolled who identify as Asian."

[[variables]]
name = "african_american_enrollment"
description = "Total number of students enrolled who identify as African American."

[[variables]]
name = "hispanic_enrollment"
description = "Total number of students enrolled who identify as Hispanic or Latino."

[[variables]]
name = "hawaiian_enrollment"
description = "Total number of students enrolled who identify as Native Hawaiian or Other Pacific Islander."

[[variables]]
name = "white_enrollment"
description = "Total number of students enrolled who identify as White."

[[variables]]
name = "two_or_more_races_enrollment"
description = "Total number of students enrolled who identify as having two or more races."

[[variables]]
name = "early_middle_college_enrollment"
description = "Total number of students enrolled in Early Middle College programs."

[[variables]]
name = "prekindergarten_enrollment"
description = "Total number of students enrolled in prekindergarten programs (typically for children aged 3-5)."

[[variables]]
name = "kindergarten_enrollment"
description = "Total number of students enrolled in kindergarten programs (typically for children aged 5-6)."

[[variables]]
name = "grade_1_enrollment"
description = "Total number of students enrolled in 1st grade."

[[variables]]
name = "grade_2_enrollment"
description = "Total number of students enrolled in 2nd grade."

[[variables]]
name = "grade_3_enrollment"
description = "Total number of students enrolled in 3rd grade."

[[variables]]
name = "grade_4_enrollment"
description = "Total number of students enrolled in 4th grade."

[[variables]]
name = "grade_5_enrollment"
description = "Total number of students enrolled in 5th grade."

[[variables]]
name = "grade_6_enrollment"
description = "Total number of students enrolled in 6th grade."

[[variables]]
name = "grade_7_enrollment"
description = "Total number of students enrolled in 7th grade."

[[variables]]
name = "grade_8_enrollment"
description = "Total number of students enrolled in 8th grade."

[[variables]]
name = "grade_9_enrollment"
description = "Total number of students enrolled in 9th grade."

[[variables]]
name = "grade_10_enrollment"
description = "Total number of students enrolled in 10th grade."

[[variables]]
name = "grade_11_enrollment"
description = "Total number of students enrolled in 11th grade."

[[variables]]
name = "grade_12_enrollment"
description = "Total number of students enrolled in 12th grade."

[[variables]]
name = "ungraded_enrollment"
description = "Total number of students enrolled in programs that do not have a specific grade level designationled."

[[variables]]
name = "economic_disadvantaged_enrollment"
description = "Total number of students enrolled who are identified as economically disadvantaged."

[[variables]]
name = "special_education_enrollment"
description = "Total number of students enrolled in special education programs."

[[variables]]
name = "english_language_learners_enrollment"
description = "Total number of students enrolled who are identified as English Language Learners (ELL), or students whose primary language is not English."

[editions.2024-06-29]
edition_date = "2024-07-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Education\\Student counts\\Data\\2024\\Raw\\student_count_2024.csv"
start = "2023-07-01"
end = "2024-06-29"
published = "??" #TODO
acquired = "??" #TODO
